### ISSUE TITLE
Problem with integer(min, max) method

### ISSUE THREAD

**Issue by RLJ05** [kristopolous/jsrand#1]
It will return the min, max integers at a ratio of 0.5 compared to numbers within the range [min+1, max-1] inclusive.

**Comment by kristopolous** [comment]
Thanks I'll check it out
On May 6, 2015 12:50 PM, RLJ05 notifications@github.com wrote:It will return the min, max integers at a ratio of 0.5 compared to numbers within the range [min+1, max-1] inclusive.

**Comment by kristopolous** [comment]
So you are expecting `(a, b)` and not `[a, b]` using the notation from http://en.wikipedia.org/wiki/Interval_%28mathematics%29#Including_or_excluding_endpoints ... valid.  Let me make this clear.

**Comment by RLJ05** [comment]
It does return [a, b] now, but a and b are going to be less frequent than any other integer.

**Comment by kristopolous** [comment]
oh i see your objection ... valid.

**Comment by kristopolous** [comment]
Ok there's a few changes:
- I have put in the qunit testing framework and written a few tests
- There's a test that looks for distribution amongst 9 or 11 buckets over a 50k sample size with +/- 4% tolerance ( it's satisfied )
- I've added a parameter to specify whether to generate within an inclusive or exclusive set on an instance wide basis.
